### ISSUE TITLE
Hide MyReactions to specific usergroups

### ISSUE THREAD

**Issue by Eldenroot** [MattRogowski/MyReactions#17]
Add a setting to hide MyReactions to selected usergroups (guests, banned, etc)

**Comment by Eldenroot** [comment]
Thx, it would be better to offer admins more than just hard code these two usergroups... anyway it covers over 99% of cases.

EDIT: I am sorry, I didnt see #21

**Comment by MattRogowski** [comment]
Yeah, created a new ticket (#21) for finer control in next release
