### ISSUE TITLE
Total reaction given/received in member profile page and postbit

### ISSUE THREAD

**Issue by Eldenroot** [MattRogowski/MyReactions#2]
Total reaction given/received in member profile page

![myreactions_profile](https://cloud.githubusercontent.com/assets/778890/19222992/1a4ec906-8e65-11e6-9feb-82680cd8dffd.png)

**Comment by MattRogowski** [comment]
- [x] Profile page
- [x] Postbit

**Comment by MattRogowski** [comment]
![screen shot 2016-10-15 at 21 19 14](https://cloud.githubusercontent.com/assets/545339/19413140/28e60ecc-931d-11e6-837e-fd08f054cb02.png)
![screen shot 2016-10-15 at 21 19 24](https://cloud.githubusercontent.com/assets/545339/19413141/3138220e-931d-11e6-90fa-72cc4ef8bb0d.png)

**Comment by Eldenroot** [comment]
Maybe it would be better to use different lang strings for postbit and for member_profile. It will allow easier customization.

Anyway it looks great! Thank you!

**Comment by Eldenroot** [comment]
Thank you @MattRogowski !
