### ISSUE TITLE
Change the design of the post content in add reaction window

### ISSUE THREAD

**Issue by Eldenroot** [MattRogowski/MyReactions#24]
I know, it is a testing version and many changes will come hen you have some spare time.

This will need a a little love - it looks ugly when you add reactions to the post with quotes or html tags - it shows text in a source mode.

![postcontent](https://cloud.githubusercontent.com/assets/778890/19419490/f6429352-93d8-11e6-9da0-6b84a6fac519.png)

I dont know how to change it, it is quite useful. Maybe you can add a username, avatar and formatted text. It is up to you, I will try to figure out and give you some ideas if you wish.

**Comment by MattRogowski** [comment]
Just stripped all the MyCode so it's a plaintext message - want to try and keep it as clean as possible really regarding adding anything else in.

**Comment by Eldenroot** [comment]
Yeah, I was thinking about this. Good job, I will test the new GitHub version in the evening

EDIT:
hr tags from post merge is not parsed, anything else is fine
