### ISSUE TITLE
Modal window - issue with a lot of reactions

### ISSUE THREAD

**Issue by Eldenroot** [MattRogowski/MyReactions#26]
When any post has a lot of reactions - the modal window is not fully shown - the top and the bottom of the window is missing - you cannot change the tab to "By reaction"/"By author"/"By time". The list is scrollable but the header is not shown (out of window)

I have to zoom out content in my browser (Ctrl+ -) - Google Chrome

![modal](https://cloud.githubusercontent.com/assets/778890/19420229/216ed7da-93e7-11e6-8861-0ba653435bb8.png)

**Comment by MattRogowski** [comment]
Hmm, obviously the 800px max height I gave it is still too tall 😛

**Comment by MattRogowski** [comment]
That better? :)

**Comment by Eldenroot** [comment]
I will try when I get home (about 18:00 CET)

EDIT: Yes, I can confirm - works without any issue
