### ISSUE TITLE
Member profile - Top received/given reaction - show all in a modal

### ISSUE THREAD

**Issue by Eldenroot** [MattRogowski/MyReactions#29]
Limit is hard coded to 10 reactions - maybe there could be a modal window (button - something like "Who reacted") where you can see all given/received reactions. Only top 10 will be there as it is now. 

Only make it simple, so show all reactions in a grid with its number (same design as in postbit)

**Comment by MattRogowski** [comment]
Thinking about it, would be quite easy to have the same as "who reacted", with lists by reaction, time and user. The code for it is pretty much already there so wouldn't take long to do.

**Comment by Eldenroot** [comment]
Great! It would be really nice feature! Thank you!

**Comment by MattRogowski** [comment]
Added it in but just realised it only really works for the 'received' one, need to change it for 'given'.

**Comment by Eldenroot** [comment]
I am looking forward ;)

EDIT:
@MattRogowski 

I like it! You put all what I want into one modal. No need for any extra page with list. Great job!

However I think there would be an issue when the user will have 1000 reactions from 1000 users. It would be a huge modal with a lot lines of usernames. 

**Feature request:**
Add a next collumn with a counter next to every reaction how many times you received/given in a modal in "By reaction" tab.
![counter](https://cloud.githubusercontent.com/assets/778890/19485652/f78c328e-955b-11e6-8b85-fe3c8da6f6b7.png)

**OR**

Make another modal with a grid view of all reactions with a small counter
![grid_view](https://cloud.githubusercontent.com/assets/778890/19485894/b9983094-955c-11e6-99bc-74b266e64497.png)

I am sorry, I am not a designer :(

**Comment by MattRogowski** [comment]
Applied my last change for this for now

**Comment by Eldenroot** [comment]
Yeah, it looks clean and has an unified design. +1. Thank you!
