### ISSUE TITLE
Total reactions given/received in XX posts statistics

### ISSUE THREAD

**Issue by Eldenroot** [MattRogowski/MyReactions#33]
Can you please add variables which extend the usability and customization? I am looking for this:

- total reactions received in "Who reacted" button in postbit (or show the total number of reactions in the post somewhere - modal? Add counter next to the "+" button?

** first idea (not bad but it needs better idea)
![total reactions in post](https://cloud.githubusercontent.com/assets/778890/20443336/c1df61cc-adcc-11e6-955c-7aabac63a39c.png)

- in postbit_profile or in member_profile (it suits better):
** XX reactions given in YY posts
** XX reactions received in YY posts
*** I think that in member_profile looks much better (dont like a lot of text in postbit template)
![statisctic](https://cloud.githubusercontent.com/assets/778890/20443364/da67d080-adcc-11e6-9202-dda0abf9da4f.png)
![statisctic2](https://cloud.githubusercontent.com/assets/778890/20443365/da69a7de-adcc-11e6-9faa-b7bfd5288bf6.png)

**Comment by MattRogowski** [comment]
Have added the number of reactions to the 'who reacted' button, think it's probably the best place for it

**Comment by Eldenroot** [comment]
Thank you!
