### ISSUE TITLE
Design improvements

### ISSUE THREAD

**Issue by Eldenroot** [MattRogowski/MyReactions#34]
I created a new issue (closed the old one #6 ). There is a summary of my ideas how to improve your plugin:

1) Add a CSS class (if possible) for "Add reaction" and "Who reacted button" for easier customization
2) Add a CSS class for given reactions under the post for the user who added them - I mean, when the post has 3x reaction "A" and 2x reaction "B" (given by other users) and the user add reaction "B" -> change the style (background, border, whatever depends on CSS styling) of the given reaction (in that case reaction "B"). 
***Here is the example - user added the third and fourth reaction - it is highlighted (different border color) - for this purpose, just add a CSS class, use same style by default.
![highlighted](https://cloud.githubusercontent.com/assets/778890/20443768/8f72c984-adce-11e6-84c3-9915a32ac840.png)

Other bug reports/ideas from the #6 are invalid or seem to be useless. Thank you for your feedback, I am looking for v1.0.

**Comment by MattRogowski** [comment]
The classes should be `reaction-add` and `reaction-reacted` for the two buttons.

I've made the border 2px, but also made it green, as the grey didn't stand out without making it darker. I also changed it to be red on hover, to make it clearer this is how you remove it - what do you think?
<img width="479" alt="screen shot 2016-12-30 at 21 57 41" src="https://cloud.githubusercontent.com/assets/545339/21573335/235f1f1c-cedb-11e6-9d70-de455ad29c34.png">

**Comment by MattRogowski** [comment]
Closing for now, can reopen if any comments :)

**Comment by Eldenroot** [comment]
Looks really good! Thank you Matt!
