### ISSUE TITLE
Link to user's profile page in postbit

### ISSUE THREAD

**Issue by Eldenroot** [MattRogowski/MyReactions#35]
Hi @MattRogowski - I am trying to add a clickable link to postbit for MyReactions for counter (number of received reactions) which will redirect you to the user's profile after click (author of the post). Is there any MyBB variable for this? I cannot find any solution. Thank you

**Comment by MattRogowski** [comment]
Made the numbers open the modals, the same as they do on profiles - thought that was better than just redirecting to the whole profile? :)

**Comment by Eldenroot** [comment]
Amazing!
