### ISSUE TITLE
Show post with highest number of reactions

### ISSUE THREAD

**Issue by MattRogowski** [MattRogowski/MyReactions#36]
Under the reacted/given lists on the profile, some way of seeing which post received the most reactions

**Comment by Eldenroot** [comment]
What about to change the border/background color of the whole post? (I mean in the thread, or make this post sticked on the top of the other posts).

**Comment by Eldenroot** [comment]
@MattRogowski - I saw your result on MyBB.com. Great! One more question - is possible to on/off in ACP?
