### ISSUE TITLE
Cannot click on the first "Add reaction" button in a thread

### ISSUE THREAD

**Issue by Eldenroot** [MattRogowski/MyReactions#39]
Difficult to describe, anyway I will try:
1) Create a new thread
2) Post one or more posts b you (#1)
3) Post one or more posts by other user (#2)
4) Try to add (as a user #1 - thread author) reaction to the post from the user #2 
5) -> no popup window, only this error in my browser console
`Uncaught SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at /jscripts/jquery.js?ver=1806:2:2622
    at Function.globalEval (/jscripts/jquery.js?ver=1806:2:2633)
    at m.fn.init.domManip (/jscripts/jquery.js?ver=1806:4:23107)
    at m.fn.init.append (/jscripts/jquery.js?ver=1806:4:20620)
    at m.fn.init.m.fn.(anonymous function) [as appendTo] (/jscripts/jquery.js?ver=1806:4:23434)
    at Object.success (/jscripts/general.js?ver=1807:81:12)
    at j (/jscripts/jquery.js?ver=1806:2:27309)
    at Object.fireWith [as resolveWith] (/jscripts/jquery.js?ver=1806:2:28122)
    at x (/jscripts/jquery.js?ver=1806:5:22111)`

6) For other posts (every other except the first one with my reactions button "Add Reaction" it works fine without any issue

![console](https://cloud.githubusercontent.com/assets/778890/21577017/dc286ec6-cf4a-11e6-93a5-a5d20902295d.png)

**Comment by MattRogowski** [comment]
Hm, I can't reproduce this... in the dev tools, can you go to Network, and look at the result of the AJAX request and see what it's doing?

**Comment by Eldenroot** [comment]
@MattRogowski - I will ASAP, I can provide your a testing account (fresh MyBB install)

**Comment by Eldenroot** [comment]
OK, here it is :(
Response:
`<div class="modal">
	<div class="myreactions-react">
		<table border="0" cellspacing="0" cellpadding="5" class="tborder">
			<tr>
				<td class="thead"><strong>Add Reaction</strong></td>
			</tr>
			<tr>
				<td class="trow1">Okay try this:


Code:
--

<script type="text/javascript">
!function($) {
    var myDiv,
		closeButton;

    function init() {
    ...</td>
			</tr>
			<tr>
	<td class="tcat">Favourite Reactions</td>
</tr>
<tr>
	<td class="trow1" align="left">
		<img src="http://testingpage.4fan.cz/images/reactions/clap.png" onclick="MyReactions.react(6,6);" title="Clap" /><img src="http://testingpage.4fan.cz/images/reactions/heart.png" onclick="MyReactions.react(25,6);" title="Heart" /><img src="http://testingpage.4fan.cz/images/reactions/grimacing.png" onclick="MyReactions.react(21,6);" title="Grimacing" /><img src="http://testingpage.4fan.cz/images/reactions/confused.png" onclick="MyReactions.react(8,6);" title="Confused" /><img src="http://testingpage.4fan.cz/images/reactions/smiling_imp.png" onclick="MyReactions.react(51,6);" title="Smiling Imp" /><img src="http://testingpage.4fan.cz/images/reactions/stuck_out_tongue.png" onclick="MyReactions.react(56,6);" title="Stuck Out Tongue" />
	</td>
</tr>
			
			<tr>
				<td class="tcat">All Reactions</td>
			</tr>
			<tr>
				<td class="trow1" align="left">
					<img src="http://testingpage.4fan.cz/images/reactions/angry.png" onclick="MyReactions.react(1,6);" title="Angry" /><img src="http://testingpage.4fan.cz/images/reactions/anguished.png" onclick="MyReactions.react(2,6);" title="Anguished" /><img src="http://testingpage.4fan.cz/images/reactions/awesome.png" onclick="MyReactions.react(3,6);" title="Awesome" /><img src="http://testingpage.4fan.cz/images/reactions/balloon.png" onclick="MyReactions.react(4,6);" title="Balloon" /><img src="http://testingpage.4fan.cz/images/reactions/broken_heart.png" onclick="MyReactions.react(5,6);" title="Broken Heart" /><img src="http://testingpage.4fan.cz/images/reactions/clap.png" onclick="MyReactions.react(6,6);" title="Clap" /><img src="http://testingpage.4fan.cz/images/reactions/confounded.png" onclick="MyReactions.react(7,6);" title="Confounded" /><img src="http://testingpage.4fan.cz/images/reactions/confused.png" onclick="MyReactions.react(8,6);" title="Confused" /><img src="http://testingpage.4fan.cz/images/reactions/crossed_fingers.png" onclick="MyReactions.react(9,6);" title="Crossed Fingers" /><img src="http://testingpage.4fan.cz/images/reactions/disappointed.png" onclick="MyReactions.react(10,6);" title="Disappointed" /><img src="http://testingpage.4fan.cz/images/reactions/disappointed_relieved.png" onclick="MyReactions.react(11,6);" title="Disappointed Relieved" /><img src="http://testingpage.4fan.cz/images/reactions/disapproval.png" onclick="MyReactions.react(12,6);" title="Disapproval" /><img src="http://testingpage.4fan.cz/images/reactions/dizzy_face.png" onclick="MyReactions.react(13,6);" title="Dizzy Face" /><img src="http://testingpage.4fan.cz/images/reactions/expressionless.png" onclick="MyReactions.react(14,6);" title="Expressionless" /><img src="http://testingpage.4fan.cz/images/reactions/eyes.png" onclick="MyReactions.react(15,6);" title="Eyes" /><img src="http://testingpage.4fan.cz/images/reactions/face_with_rolling_eyes.png" onclick="MyReactions.react(16,6);" title="Face With Rolling Eyes" /><img src="http://testingpage.4fan.cz/images/reactions/facepalm.png" onclick="MyReactions.react(17,6);" title="Facepalm" /><img src="http://testingpage.4fan.cz/images/reactions/fearful.png" onclick="MyReactions.react(18,6);" title="Fearful" /><img src="http://testingpage.4fan.cz/images/reactions/fire.png" onclick="MyReactions.react(19,6);" title="Fire" /><img src="http://testingpage.4fan.cz/images/reactions/flushed.png" onclick="MyReactions.react(20,6);" title="Flushed" /><img src="http://testingpage.4fan.cz/images/reactions/grimacing.png" onclick="MyReactions.react(21,6);" title="Grimacing" /><img src="http://testingpage.4fan.cz/images/reactions/grin.png" onclick="MyReactions.react(22,6);" title="Grin" /><img src="http://testingpage.4fan.cz/images/reactions/grinning.png" onclick="MyReactions.react(23,6);" title="Grinning" /><img src="http://testingpage.4fan.cz/images/reactions/hear_no_evil.png" onclick="MyReactions.react(24,6);" title="Hear No Evil" /><img src="http://testingpage.4fan.cz/images/reactions/heart.png" onclick="MyReactions.react(25,6);" title="Heart" /><img src="http://testingpage.4fan.cz/images/reactions/heart_eyes.png" onclick="MyReactions.react(26,6);" title="Heart Eyes" /><img src="http://testingpage.4fan.cz/images/reactions/ill.png" onclick="MyReactions.react(27,6);" title="Ill" /><img src="http://testingpage.4fan.cz/images/reactions/information_desk_person.png" onclick="MyReactions.react(28,6);" title="Information Desk Person" /><img src="http://testingpage.4fan.cz/images/reactions/innocent.png" onclick="MyReactions.react(29,6);" title="Innocent" /><img src="http://testingpage.4fan.cz/images/reactions/joy.png" onclick="MyReactions.react(30,6);" title="Joy" /><img src="http://testingpage.4fan.cz/images/reactions/laughing.png" onclick="MyReactions.react(31,6);" title="Laughing" /><img src="http://testingpage.4fan.cz/images/reactions/mask.png" onclick="MyReactions.react(32,6);" title="Mask" /><img src="http://testingpage.4fan.cz/images/reactions/nerd_face.png" onclick="MyReactions.react(33,6);" title="Nerd Face" /><img src="http://testingpage.4fan.cz/images/reactions/neutral_face.png" onclick="MyReactions.react(34,6);" title="Neutral Face" /><img src="http://testingpage.4fan.cz/images/reactions/ok_hand.png" onclick="MyReactions.react(35,6);" title="Ok Hand" /><img src="http://testingpage.4fan.cz/images/reactions/open_mouth.png" onclick="MyReactions.react(36,6);" title="Open Mouth" /><img src="http://testingpage.4fan.cz/images/reactions/pensive.png" onclick="MyReactions.react(37,6);" title="Pensive" /><img src="http://testingpage.4fan.cz/images/reactions/persevere.png" onclick="MyReactions.react(38,6);" title="Persevere" /><img src="http://testingpage.4fan.cz/images/reactions/poop.png" onclick="MyReactions.react(39,6);" title="Poop" /><img src="http://testingpage.4fan.cz/images/reactions/pray.png" onclick="MyReactions.react(40,6);" title="Pray" /><img src="http://testingpage.4fan.cz/images/reactions/rage.png" onclick="MyReactions.react(41,6);" title="Rage" /><img src="http://testingpage.4fan.cz/images/reactions/raised_hands.png" onclick="MyReactions.react(42,6);" title="Raised Hands" /><img src="http://testingpage.4fan.cz/images/reactions/rofl.png" onclick="MyReactions.react(43,6);" title="Rofl" /><img src="http://testingpage.4fan.cz/images/reactions/scream.png" onclick="MyReactions.react(44,6);" title="Scream" /><img src="http://testingpage.4fan.cz/images/reactions/see_no_evil.png" onclick="MyReactions.react(45,6);" title="See No Evil" /><img src="http://testingpage.4fan.cz/images/reactions/shrug.png" onclick="MyReactions.react(46,6);" title="Shrug" /><img src="http://testingpage.4fan.cz/images/reactions/sleeping.png" onclick="MyReactions.react(47,6);" title="Sleeping" /><img src="http://testingpage.4fan.cz/images/reactions/slightly_frowning_face.png" onclick="MyReactions.react(48,6);" title="Slightly Frowning Face" /><img src="http://testingpage.4fan.cz/images/reactions/slightly_smiling_face.png" onclick="MyReactions.react(49,6);" title="Slightly Smiling Face" /><img src="http://testingpage.4fan.cz/images/reactions/smile.png" onclick="MyReactions.react(50,6);" title="Smile" /><img src="http://testingpage.4fan.cz/images/reactions/smiling_imp.png" onclick="MyReactions.react(51,6);" title="Smiling Imp" /><img src="http://testingpage.4fan.cz/images/reactions/smirk.png" onclick="MyReactions.react(52,6);" title="Smirk" /><img src="http://testingpage.4fan.cz/images/reactions/sob.png" onclick="MyReactions.react(53,6);" title="Sob" /><img src="http://testingpage.4fan.cz/images/reactions/speak_no_evil.png" onclick="MyReactions.react(54,6);" title="Speak No Evil" /><img src="http://testingpage.4fan.cz/images/reactions/star.png" onclick="MyReactions.react(55,6);" title="Star" /><img src="http://testingpage.4fan.cz/images/reactions/stuck_out_tongue.png" onclick="MyReactions.react(56,6);" title="Stuck Out Tongue" /><img src="http://testingpage.4fan.cz/images/reactions/stuck_out_tongue_closed_eyes.png" onclick="MyReactions.react(57,6);" title="Stuck Out Tongue Closed Eyes" /><img src="http://testingpage.4fan.cz/images/reactions/stuck_out_tongue_winking_eye.png" onclick="MyReactions.react(58,6);" title="Stuck Out Tongue Winking Eye" /><img src="http://testingpage.4fan.cz/images/reactions/sunglasses.png" onclick="MyReactions.react(59,6);" title="Sunglasses" /><img src="http://testingpage.4fan.cz/images/reactions/suspicious.png" onclick="MyReactions.react(60,6);" title="Suspicious" /><img src="http://testingpage.4fan.cz/images/reactions/sweat.png" onclick="MyReactions.react(61,6);" title="Sweat" /><img src="http://testingpage.4fan.cz/images/reactions/sweat_smile.png" onclick="MyReactions.react(62,6);" title="Sweat Smile" /><img src="http://testingpage.4fan.cz/images/reactions/tada.png" onclick="MyReactions.react(63,6);" title="Tada" /><img src="http://testingpage.4fan.cz/images/reactions/thinking_face.png" onclick="MyReactions.react(64,6);" title="Thinking Face" /><img src="http://testingpage.4fan.cz/images/reactions/thumbsdown.png" onclick="MyReactions.react(65,6);" title="Thumbsdown" /><img src="http://testingpage.4fan.cz/images/reactions/thumbsup.png" onclick="MyReactions.react(66,6);" title="Thumbsup" /><img src="http://testingpage.4fan.cz/images/reactions/tired_face.png" onclick="MyReactions.react(67,6);" title="Tired Face" /><img src="http://testingpage.4fan.cz/images/reactions/triumph.png" onclick="MyReactions.react(68,6);" title="Triumph" /><img src="http://testingpage.4fan.cz/images/reactions/unamused.png" onclick="MyReactions.react(69,6);" title="Unamused" /><img src="http://testingpage.4fan.cz/images/reactions/upside_down_face.png" onclick="MyReactions.react(70,6);" title="Upside Down Face" /><img src="http://testingpage.4fan.cz/images/reactions/v.png" onclick="MyReactions.react(71,6);" title="V" /><img src="http://testingpage.4fan.cz/images/reactions/whatever.png" onclick="MyReactions.react(72,6);" title="Whatever" /><img src="http://testingpage.4fan.cz/images/reactions/white_frowning_face.png" onclick="MyReactions.react(73,6);" title="White Frowning Face" /><img src="http://testingpage.4fan.cz/images/reactions/wink.png" onclick="MyReactions.react(74,6);" title="Wink" /><img src="http://testingpage.4fan.cz/images/reactions/worried.png" onclick="MyReactions.react(75,6);" title="Worried" /><img src="http://testingpage.4fan.cz/images/reactions/zipper_mouth_face.png" onclick="MyReactions.react(76,6);" title="Zipper Mouth Face" />
				</td>
			</tr>
		</table>
	</div>
</div>`

Header:
`Request URL:http://testingpage.4fan.cz/misc.php?action=myreactions&pid=6
Request Method:GET
Status Code:200 OK
Remote Address:88.86.120.111:80
Response Headers
view source
Connection:close
Content-Language:cs
Content-Type:text/html
Date:Sun, 01 Jan 2017 12:35:28 GMT
Server:nginx
Transfer-Encoding:chunked
X-Powered-By:PHP/7.0.10
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:cs,en-GB;q=0.8,en;q=0.6
Connection:keep-alive
Cookie:collapsed=; mybb[lastvisit]=1480850550; mybb[lastactive]=1480877614; loginattempts=1; mybbuser=1_T35vilVkO6TKIdQvYoe0qMjIpt5U2CaFNwKm13wsOFij2MR3uc; _ga=GA1.3.1775190459.1469351746; __ar_v4=%7CLBMQLP6YHJFG7KXWFPVCV3%3A20170004%3A1%7CYD4FELB2FFDBVPM3JHRFB4%3A20170004%3A1%7CNUH4TFHP6VF4FJ2GL6ZKBD%3A20170004%3A1; _ga=GA1.2.1775190459.1469351746; inlinemod_thread1=%7C4%7C; inlinemod_thread2=%7C12%7C; sid=ef22f0cabd98c0db6bb4b75d6423eba9
Host:testingpage.4fan.cz
Referer:http://testingpage.4fan.cz/showthread.php?tid=3
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.28 Safari/537.36
X-Requested-With:XMLHttpRequest
Query String Parameters
view source
view URL encoded
action:myreactions
pid:6`

**Comment by Eldenroot** [comment]
I find the issue, **it is due to the content in the post - when you insert the attachment into the post content + php code block together.** After that the Add reaction button is not working. I sent you all info via PM in MyBB.com community forum

**Comment by Eldenroot** [comment]
@MattRogowski - can you please release at least a minor version with fix for this (full version would be better anyway) 👍 :)
