### ISSUE TITLE
Select predefined reactions

### ISSUE THREAD

**Issue by Eldenroot** [MattRogowski/MyReactions#4]
Add an option to admin select X predefined default reactions which would be added automatically to the myreactions into post - poster can change them

**Comment by MattRogowski** [comment]
Do you mean they'd actually be applied to the post, or just ones that show in the postbit all the time? I'm not sure if it's the same as what I intended for #10 or not.

**Comment by Eldenroot** [comment]
I mean something like this on GitHub:

![predefined reactions](https://cloud.githubusercontent.com/assets/778890/19417861/b4ecf44a-93b7-11e6-9123-d9335c36970f.png)

Admin will choose only for example 5 icons which cannot be changed by user (I am not sure about this point). User can add only one reaction to the post, not more.

**Comment by MattRogowski** [comment]
Yeah that's pretty much what I was going to do in #10 so will keep there for now
