### ISSUE TITLE
MyISAM db - question

### ISSUE THREAD

**Issue by Eldenroot** [MattRogowski/MyReactions#40]
Hi @MattRogowski - is there any way how to make your plugin compatible with MyISAM db without changing InnoDB to MyISAM in your plugin file?

I am asking, because on my live board I use InnoDB which is fine, but on my testing board I use MyISAM (InnoDB is not available due to free webhosting). 

I am not sure how many MyBB users uses MyISAM/InnoDB. It would bring support questions and invalid bug reports for unskilled users in future.

If it would be possible it would be better to make your plugin compatible with both of them (if it is easy and not time consuming). Just an idea, feel free to close this. Thank you!

**Comment by MattRogowski** [comment]
Have changed to MyISAM, only reason it was set to InnoDB was because of the setting on my local machine when I created the table, was no real reason to have it as InnoDB.

**Comment by Eldenroot** [comment]
@MattRogowski - what if someone uses InnoDB? Does it require change back to InnoDB? I am sorry, but this is not my cup of coffee

**Comment by MattRogowski** [comment]
Is fine for it to stay at InnoDB, just makes more sense to create it with MyISAM, which is the same as the default MyBB tables.

**Comment by Eldenroot** [comment]
I am sorry, I mean - is needed to change MyISAM to InnoDB in plugin file for all users whose use InnoDB after this commit?

**Comment by MattRogowski** [comment]
No, won't need to change anything, the actual table will stay as InnoDB but like I say, makes no difference so will be fine :)
