### ISSUE TITLE
Add a variable for total reactions given/received output in postbit under the user´s avatar

### ISSUE THREAD

**Issue by Eldenroot** [MattRogowski/MyReactions#5]
Add a variable for total reactions given/received output in postbit under the user´s avatar.

**Comment by MattRogowski** [comment]
This will actually be covered by #2 so will close this one

**Comment by Eldenroot** [comment]
Will be there any way how to show it in postbit under member´s avatar in statistic (threads, posts, ...)?

**Comment by MattRogowski** [comment]
Yep :) Will use the same variable/column so just condensing to one ticket.
