### ISSUE TITLE
What happen on user deletion?

### ISSUE THREAD

**Issue by Eldenroot** [MattRogowski/MyReactions#50]
I am just wonder - what happen to given/added reactions when the user is deleted/pruned. The reactions should be deleted too, are they? Thank you!

**Comment by MattRogowski** [comment]
They'll probably be cleared up by the recount and rebuild task in #41

**Comment by Eldenroot** [comment]
Good, because there could be an issue with spammers whose spam every post. After pruning them, the reactions will be deleted so it is great. I am closing this.
