### ISSUE TITLE
Emoji size doesn't change

### ISSUE THREAD

**Issue by alansharkey** [MattRogowski/MyReactions#56]
The config options lists 5 sizes, but changing them (and saving) doesn't change the size of the emoji displayed - it's quite large.

I have it set as grouped. I tried linear but that made no difference.

Version seems to be 0.0.4 on my BB system (cb1300.createmybb4.com)

**Comment by MattRogowski** [comment]
You don't seem to have the CSS file installed, there's steps in the readme to add it as it's not done automatically when installing the plugin.
