### ISSUE TITLE
List of users whose added reactions to the post

### ISSUE THREAD

**Issue by Eldenroot** [MattRogowski/MyReactions#6]
It is quite tricky - it needs a simply but useful list of users who reacted. Maybe take a concept from Facebook? I have no idea how to make it easily.

**Comment by MattRogowski** [comment]
I'll do this as a modal, will be the cleanest way I think without cluttering up the postbit.

**Comment by Eldenroot** [comment]
Yeah, I agree. I am looking for a new release! I hope it will be there sooner than later, cannot wait :(

**Comment by MattRogowski** [comment]
Will do my best :D

**Comment by Eldenroot** [comment]
Really good feedback from the users in my board, I replaced Thank you/like plugin and disabled MyBB rep system... just make things easier. I am free for testing - just let me know :)

**Comment by MattRogowski** [comment]
![screen shot 2016-10-16 at 12 47 15](https://cloud.githubusercontent.com/assets/545339/19417201/b884650c-939e-11e6-89a2-3aad9712032f.png)
Will then open a modal

**Comment by Eldenroot** [comment]
OK, looks nice - maybe the icon would be changed. Will we see who added the specific reaction? For example:

User A - added heart and star
User B - added baloon

etc?

**Comment by MattRogowski** [comment]
The icon will just be in a template so will be able to change to whatever you like.

And yes, will be able to see that 😀

**Comment by Eldenroot** [comment]
Amazing ;)

**Comment by MattRogowski** [comment]
![screen shot 2016-10-16 at 16 18 02](https://cloud.githubusercontent.com/assets/545339/19418462/51d1b26a-93bc-11e6-912f-2570ad8933b0.png)
![screen shot 2016-10-16 at 16 18 21](https://cloud.githubusercontent.com/assets/545339/19418464/54f24dba-93bc-11e6-8c3a-7528f3f9e5fb.png)
![screen shot 2016-10-16 at 16 19 17](https://cloud.githubusercontent.com/assets/545339/19418465/570c5122-93bc-11e6-8cc4-c879aaa779b7.png)
Here we go :)

**Comment by Eldenroot** [comment]
Amazing! Great! Just two questions:
1) is possible to customise the time output? Any settings for this?
2) Does it show on mouse hover (title tag) on username in "By reaction" tab time when the reaction was added? Or mouse hover on smile what is it?

**Comment by MattRogowski** [comment]
The time format will be the same as the rest of the forum as uses the same settings.

As for the title tag, it only shows the names of the reactions when you hover over the images - I didn't really want to clutter it up too much with too much in the title tags. It's kinda awkward to use title tags with the inbuilt profile link function too.

**Comment by Eldenroot** [comment]
OK, I agree, you are right. Keep good work! ;)

**Comment by Eldenroot** [comment]
1) and 2) nevermind

3) **And one important thing - you should leave "+"  and "who reacted" buttons visible - check n. 5

4) Is possible to highlight the given reactions by the user in the list under the post? (it is missaligned due to my issue, not related to your plugin)
![border](https://cloud.githubusercontent.com/assets/778890/19419356/1051ce50-93d6-11e6-9cb4-13455d58f499.png)

5) Do not hide "who reacted" button - maybe you can divide the reaction by "|" symbol and change the text to the user image (http://simpleicon.com/wp-content/uploads/multy-user.png for example). So the "+ add reaction" and "who reacted" buttons will be separated from reactions buttons

6) "Who reacted" button is missaligned for the author of the post when it got any reactions. Also why to change opacity on hover? 
![bug5](https://cloud.githubusercontent.com/assets/778890/19419820/cbd721f8-93df-11e6-9d46-3e4ef297dec8.png)

Srry for my bug report in one message, I can create a special issue for this if you wanna

**Comment by Eldenroot** [comment]
@MattRogowski - hi, just a question - is there any CSS class to set different style for given reactions under the post by me? I would like to highlight them

**Comment by Eldenroot** [comment]
I am closing this, it is done and I created a new issue #34
