### ISSUE TITLE
Thank you/like system mod - converter to MyReactions

### ISSUE THREAD

**Issue by Eldenroot** [MattRogowski/MyReactions#7]
Yes, it is maybe weird that I wanna a converter from the plugin which I maintain :)

https://github.com/Cu8eR/MyBB_Thank-you-like-plugin

but a lot of users wrote me to add features which I wont add to my Thank you/like plugin. However MyReactions (when will be ready with all features in a stable version) will contain a lot of things which were asked. It would be nice to make an option to easily convert.

**Comment by Eldenroot** [comment]
Maybe you can use this - import from Thank you/like system into MyBB default reputation system

`INSERT INTO mybb_reputation (uid, adduid, pid, reputation, dateline, comments) SELECT puid AS uid, uid, pid, 1, dateline, 'Imported from Thankyou/Like' FROM mybb_thankyoulike;`

**Comment by MattRogowski** [comment]
Yeah, I'll have an importer for all the other thank you and like plugins - I planned to allow you to choose a reaction (probably the thumbs up emoji) and it'd change all thank yous/likes to that.

**Comment by MattRogowski** [comment]
Think I'm about done with this! 🎉
